name: Label Issues and PRs

on:
- pull_request
- issues

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: srvaroa/labeler@v1.10.1
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
