name: Downstream

on:
  workflow_dispatch:
    inputs:
      nightly:
        default: ""
  workflow_call:
    inputs:
      nightly:
        type: string
        default: ""

permissions:
  contents: read
  id-token: write

jobs:
  rufus:
    name: Rufus
    runs-on: ubuntu-24.04
    if: ${{ !github.event.pull_request || github.event.pull_request.author_association == 'MEMBER' }}
    steps:
      - name: Rufus
        uses: cicada/github-actions/downstream@main
        with:
          repo: cicada/rufus
          workflow: Downstream
          ref: trunk
          timeout: 15m
          env:
            NIGHTLY=${{ inputs.nightly }}

  commercial:
    name: Commercial
    runs-on: ubuntu-24.04
    if: ${{ !github.event.pull_request || github.event.pull_request.author_association == 'MEMBER' }}
    steps:
      - name: Commercial
        uses: cicada/github-actions/downstream@main
        with:
          repo: cicada/SwagCommercial
          workflow: Downstream
          ref: trunk
          timeout: 20m
          env:
            NIGHTLY=${{ inputs.nightly }}
